In [157]:
import random
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [158]:
df = pd.read_csv('/Users/deepbhattacharjee/Documents/Machine learning dataset for Project/train-2.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [159]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [160]:
df.loc[df['Age'].isnull(),'Age'] = np.round(df['Age'].mean())

In [161]:
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [162]:
df['Sex'].replace(['male', 'female'],
                        [0, 1], inplace=True)

In [163]:
df['Embarked'].replace(['S', 'C','Q'],
                        [-1,0, 1], inplace=True)

In [164]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN      -1.0  
1          PC 17599  71.2833   C85       0.0  
2  STON/O2. 3101282   7.9250   NaN      -1.0  
3            113803  53.1000  C123      -1.0  
4            373450   8.0500   NaN      -1.0

In [165]:
df.loc[df['Embarked'].isnull(),'Embarked'] = df['Embarked'].value_counts().index[0]

In [166]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [167]:
df=df.drop(['Cabin'],axis=1)

In [168]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [169]:
features = ['Pclass','Sex','Age','SibSp','Parch', 'Fare', 'Embarked']
nb_train = int(np.floor(0.9 * len(df)))
df = df.sample(frac=1, random_state=217)
X_train = df[features][:nb_train]
y_train = df['Survived'][:nb_train].values
X_test = df[features][nb_train:]
y_test = df['Survived'][nb_train:].values

In [170]:
from sklearn.ensemble import RandomForestClassifier

In [171]:
clf = RandomForestClassifier(criterion = 'gini',
                             max_depth = 8,
                             min_samples_split= 10,
                             random_state = 5)

In [172]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=5)

In [173]:
clf.feature_importances_

array([0.12317064, 0.40779243, 0.14128343, 0.05069592, 0.03659936,
       0.20118336, 0.03927486])

In [174]:
y_pred = clf.predict(X_test)

In [175]:
y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0])

In [176]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[50,  3],
       [12, 25]])

In [177]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8333333333333334

In [178]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X_train, y_train, cv = 10)

array([0.71604938, 0.85      , 0.8875    , 0.8       , 0.7875    ,
       0.875     , 0.8125    , 0.8375    , 0.875     , 0.75      ])

In [179]:
df = pd.read_csv('/Users/deepbhattacharjee/Documents/Machine learning project Data set/secondary_data.csv')
df.head()

class  cap-diameter cap-shape cap-surface cap-color does-bruise-or-bleed  \
0     p         15.26         x           g         o                    f   
1     p         16.60         x           g         o                    f   
2     p         14.07         x           g         o                    f   
3     p         14.17         f           h         e                    f   
4     p         14.64         x           h         o                    f   

  gill-attachment gill-spacing gill-color  stem-height  ...  stem-root  \
0               e          NaN          w        16.95  ...          s   
1               e          NaN          w        17.99  ...          s   
2               e          NaN          w        17.80  ...          s   
3               e          NaN          w        15.77  ...          s   
4               e          NaN          w        16.53  ...          s   

  stem-surface stem-color veil-type veil-color has-ring ring-type  \
0            y          w         u          w        t         g   
1            y          w         u          w        t         g   
2            y          w         u          w        t         g   
3            y          w         u          w        t         p   
4            y          w         u          w        t         p   

  spore-print-color habitat season  
0               NaN       d      w  
1               NaN       d      u  
2               NaN       d      w  
3               NaN       d      w  
4               NaN       d      w  

[5 rows x 21 columns]

In [180]:
mapping_dict = {
    "cap-shape" : {
        "b": "bell",
        "c": "conical",
        "x": "convex",
        "f": "flat",
        "s": "sunken",
        "p": "spherical",
        "o": "others"
    },
    "cap-surface" : {
        "i": "fibrous",
        "g": "grooves",
        "y": "scaly",
        "s": "smooth",
        "h": "shiny",
        "l": "leathery",
        "k": "stilky",
        "t": "sticky",
        "w": "wrinkled",
        "e": "flashy",
        "f": "none"
    },
    "gill-attachment" : {
        "a": "adnate",
        "x": "decurrent",
        "d": "decurrent",
        "e": "free",
        "s": "sinuate",
        "p": "pores",
        "f": "none"
    },
    "gill-spacing": {
        "c": "close",
        "d": "distant",
        "f": "none"
    },
    "stem-root": {
        "b": "bulbous",
        "s": "swollen",
        "c": "club",
        "u": "cup",
        "e": "equal",
        "z": "rhizomorphs",
        "r": "rooted"
    },
    "stem-surface" : {
        "i": "fibrous",
        "g": "grooves",
        "y": "scaly",
        "s": "smooth",
        "h": "shiny",
        "l": "leathery",
        "k": "stilky",
        "t": "sticky",
        "w": "wrinkled",
        "e": "flashy",
        "f": "none"
    },
    "ring-type": {
        "c": "cobwebby",
        "c": "evanescent",
        "r": "flaring",
        "g": "grooved",
        "l": "large",
        "p": "pendant",
        "s": "sheathing",
        "z": "zone",
        "y": "scaly",
        "m": "movable",
        "f": "none",
    },
    "habitat": {
        "g": "grasses",
        "l": "leaves",
        "m": "meadows",
        "p": "paths",
        "h": "heaths",
        "u": "urban",
        "w": "waste",
        "d": "woods",
    },
    "season": {
        "s": "spring",
        "u": "summer",
        "a": "autumn",
        "w": "winter"
    }
}

for col in mapping_dict.keys():
    df = df.replace({col: mapping_dict[col]})

In [181]:
colors = {"b": "buff",
          "n": "brown",
          "g": "gray",
          "r": "green",
          "p": "pink",
          "u": "purple",
          "e": "red",
          "w": "white",
          "y": "yellow",
          "l": "blue",
          "k": "black",
          "f": "none",
          "o": "orange"}
color_cols = ['cap-color', 'gill-color', 'gill-color', 'stem-color', 'veil-color', 'spore-print-color']
for col in color_cols:
    df = df.replace({col: colors})

In [182]:
 df1 = df.fillna('Na')

In [183]:
df1.isnull().sum()

class                   0
cap-diameter            0
cap-shape               0
cap-surface             0
cap-color               0
does-bruise-or-bleed    0
gill-attachment         0
gill-spacing            0
gill-color              0
stem-height             0
stem-width              0
stem-root               0
stem-surface            0
stem-color              0
veil-type               0
veil-color              0
has-ring                0
ring-type               0
spore-print-color       0
habitat                 0
season                  0
dtype: int64

In [185]:
df1.nunique()

class                      2
cap-diameter            2571
cap-shape                  7
cap-surface               12
cap-color                 12
does-bruise-or-bleed       2
gill-attachment            7
gill-spacing               4
gill-color                12
stem-height             2226
stem-width              4630
stem-root                  6
stem-surface               9
stem-color                13
veil-type                  2
veil-color                 7
has-ring                   2
ring-type                  9
spore-print-color          8
habitat                    8
season                     4
dtype: int64

In [187]:
df2 = pd.get_dummies(df1, columns=['class','stem-root', 'cap-shape', 'cap-surface', 'cap-color',
       'does-bruise-or-bleed', 'gill-attachment', 'gill-spacing', 'gill-color',
       'stem-color','stem-surface','veil-type','veil-color','spore-print-color', 
                                   'has-ring', 'ring-type', 'habitat', 'season'], drop_first=True)

In [188]:
df2.columns = df2.columns.str.replace('-', '_')

In [191]:
X_train.shape

(801, 7)

In [192]:
from sklearn.model_selection import train_test_split

In [193]:
X = df2.drop(['class_p'], axis=1).copy()
y = df2['class_p'].copy()

In [194]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=20, test_size=0.25, stratify=y)

In [195]:
X_train.shape

(45801, 110)

In [196]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=5)

In [197]:
clf.feature_importances_

array([5.87073470e-02, 5.51156835e-02, 1.01695326e-01, 8.05795086e-03,
       1.28462397e-02, 5.12678345e-03, 2.63617008e-02, 3.30062903e-03,
       6.85575731e-03, 7.49667672e-03, 5.51262108e-03, 6.19247686e-03,
       2.54942444e-03, 2.88551077e-03, 6.86165402e-03, 6.89721318e-03,
       9.91980581e-03, 9.92575439e-03, 2.82283194e-03, 5.87582491e-03,
       4.03835775e-03, 1.44285096e-02, 8.45213854e-03, 2.35791124e-02,
       5.00419589e-03, 1.78769741e-04, 9.70151143e-03, 4.20085728e-03,
       5.34389912e-03, 1.19584170e-02, 2.74854658e-03, 2.00094684e-03,
       4.44473856e-04, 1.35966363e-02, 3.06197372e-03, 3.74920459e-03,
       1.19156585e-02, 6.66781672e-03, 1.28334635e-02, 8.93289437e-03,
       3.53112627e-03, 4.22125059e-02, 5.70291740e-03, 1.36353867e-02,
       3.65252852e-02, 6.30735830e-03, 1.17970436e-02, 8.73518502e-04,
       5.35061224e-03, 1.00212320e-03, 5.37132994e-03, 4.06166607e-03,
       6.78165189e-03, 4.29922449e-04, 2.32382786e-03, 2.17179665e-02,
      

In [198]:
y_pred = clf.predict(X_test)

In [199]:
y_pred

array([1, 1, 1, ..., 1, 0, 1], dtype=uint8)

In [200]:
accuracy_score(y_test,y_pred)

0.9300497773120252